version: "3.8"

services:
  postgres-wop:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./db:/docker-entrypoint-initdb.d

  back-wop-postgres:
    build: .
    container_name: back-wop-postgres
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - postgres-wop
    env_file:
      - .env

volumes:
  postgres-data:
